### ISSUE TITLE
Can't update post and fatal error with "Post" block

### ISSUE THREAD

**Issue by MarieComet** [maximebj/advanced-gutenberg-blocks#1]
WP 4.9.4 multisite
Gutenberg 2.4.0
Custom theme

When using "Post" block there is a notice in admin : "Mise à jour échouée" and post do not update.
Console log : 
`Block "gutenblocks/products" is not registered.
Block "gutenblocks/addtocart" is not registered.
Block "gutenblocks/products" is not registered.
Block "gutenblocks/addtocart" is not registered.`

And in front, when loading the same post after update failed : 
`Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 7 bytes) ...`

If I remove the "Post" block everything is fine.

**Comment by maximebj** [comment]
Okay I have fixed a naming error for that. 

About the memory errors : it occurs when you didn't set a real excerpt in the inspector. It seems like Gutenberg consume a lot of ressources when parsing the main content to get an excerpt

The issue is open on the official Repository here : https://github.com/WordPress/gutenberg/issues/5572
